name: cloud_firestore_odm_generator
description: A code generator for cloud_firestore_odm.
homepage: https://firebase.flutter.dev/docs/firestore/odm
repository: https://github.com/firebaseextended/firestoreodm-flutter
version: 1.3.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  analyzer: ">=6.0.0 <9.0.0"
  build: ^3.0.2
  build_config: ^1.2.0
  cloud_firestore_odm: ^1.2.0
  # For testing locally
  # cloud_firestore_odm:
  #   path: ../cloud_firestore_odm
  collection: ^1.18.0
  freezed_annotation: ^3.0.0
  # Can be removed once this is fixed https://github.com/dart-lang/graphs/issues/86
  graphs: ^2.3.1
  json_annotation: ^4.9.0
  meta: ^1.12.0
  recase: ^4.1.0
  source_gen: ^3.1.0
  source_helper: ^1.3.7

dev_dependencies:
  build_runner: ^2.7.0
  expect_error: ^1.0.10
  json_serializable: ^6.11.0
  matcher: ^0.12.17
  test: ^1.25.15
