name: cloud_firestore_odm
description: An ODM for Firebase Cloud Firestore (cloud_firestore).
homepage: https://github.com/firebaseextended/firestoreodm-flutter
repository: https://github.com/firebaseextended/firestoreodm-flutter
version: 2.0.2

false_secrets:
  - example/**

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  cloud_firestore: ^6.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.3

dependency_overrides:
  test_api: ^0.7.7
  # custom_lint_visitor: ^1.0.0+8.1.1
